### PR TITLE
stm32cube: stm32wlxx: disable SUBGHZ module

### PR DESCRIPTION
**Pull request by fabiobaltieri**
This is to support https://github.com/zephyrproject-rtos/zephyr/pull/36573, which does not use the SUBGHZ HAL. Excluding the SUBGHZ HAL module to avoid register redefinition errors.

### CODE REVIEW

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by erwango — CHANGES_REQUESTED** [review]
Please add a comment on this change in wl series README file, under Patch List:

    *<Fix description>
     Impacted files:
      -<file>

**Comment by fabiobaltieri** [comment]
> Please add a comment on this change in wl series README file, under Patch List:
> 
> ```
> *<Fix description>
>  Impacted files:
>   -<file>
> ```

Got it, done.

**Review by erwango — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
(merge conflict, rebased)

**Review by mniestroj — APPROVED** [review]

**Pull request merged**
