### PR TITLE
dts: Align -pinctrl.dtsi on STM32CubeMX 6.2.0

### PR DESCRIPTION
**Pull request by erwango**
Update pinctrl.dtsi files based on recent STM32CubeMX 6.2.0
delivery.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
^^ @str4t0m

**Review by gmarull — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by galak** [comment]
is there a zephyr side pr related to this?

**Comment by str4t0m** [comment]
The low end Cortex-m0 socs only have 6 to 7 alternative function mappings, but all mappings defined in the IP block are exported.
So we have a few extra definitions for af8, af9, ... mappings, that we could get rid of.
I think I'll open an issue that we consider this the next time the script is refactored.

**Comment by str4t0m** [comment]
Sure. I'll point at an example in a dedicated issue, as it is not really relevant for this pr.

**Pull request merged**
