### PR TITLE
STM32WB: Update BLE HCI Lib to V1.9.0

### PR DESCRIPTION
**Pull request by erwango**
Update STM32WB HCI Lib from V1.5.0 to V1.9.0
Include intermediate steps in case some issue show up.
Tested successfully in successive iterations with V1.6.0, V1.7, V1.8 and V1.9.0 binaries.

### CODE REVIEW

**Comment by erwango** [comment]
To be merged after V2.4.0 release

**Comment by tritao** [comment]
Can this be merged now?

**Comment by erwango** [comment]
@tritao Actually I need to upgrade once again (to v1.9). I'm targeting to complete this task this week.

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
