### PR TITLE
stm32cube: update stm32l4 to cube version V1.18.1

### PR DESCRIPTION
**Pull request by legoabram**
Update Cube version for STM32L4xx series
on https://github.com/STMicroelectronics
from version v1.18.0
to version v1.18.1

ST included their own version of the `ifndef` for `UNUSED`, so I removed the note that it was changed. 

All files were copied verbatim from a git cloned copy of 1.18.1, and then whitespace was modified to minimize the number of changes. Obviously this will need to be tested more, and it looks like I missed some whitespace, but I'll post this so it starts the review process. My team is in need of this change because it includes a fix for the STM32L496 which breaks 4bit SDMMC.

Once applied to zephyr, this should address: https://github.com/zephyrproject-rtos/zephyr/issues/73398

### CODE REVIEW

**Comment by erwango** [comment]
@legoabram Thanks.
You might want to use Cube package update scripts documented [here](https://github.com/zephyrproject-rtos/hal_stm32/blob/main/scripts/README.rst) to be sure you didn't forget anything.

**Comment by legoabram** [comment]
Dagnabbit. Of course you guys made a script for it. My bad. I'll readdress this next week.

**Comment by legoabram** [comment]
@erwango So close! I missed a number of white spacing inconsistencies, and two ifdefs. It's reuploaded with only the script changes. I left the `UNUSED` definition as generated by the script rather than use the new ST code. Likely need to update the script to do that, and I'll leave that up to you guys.

**Comment by erwango** [comment]
> It's reuploaded with only the script changes. I left the UNUSED definition as generated by the script rather than use the new ST code. Likely need to update the script to use the ST code, but I'll leave that up to you guys.

That's expected. The UNUSED stuff is a patch over HAL that's required in Zephyr waiting it to be delivered in ST version.

Have you been able to run non regression campaign (using twister) on this version ?

**Comment by legoabram** [comment]
> That's expected. The UNUSED stuff is a patch over HAL that's required in Zephyr waiting it to be delivered in ST version.

That's what I mean: The new ST code now has it's own "patch" to not redefine `UNUSED` if it already has been. 

> Have you been able to run non regression campaign (using twister) on this version ?

I've run every twister test on my branch with three boards: nucleo_h7a3zi_q, nucleo_g01bre, and nucleo_l476rg. There were two errors that are probably unrelated:

```
INFO    - Zephyr version: v3.7.0-2431-g5032f099c647
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/abram/Workspaces/zephyr-rtos/twister-out/testplan.json

Device testing on:
| Platform        | ID                       | Serial device   |
|-----------------|--------------------------|-----------------|
| nucleo_h7a3zi_q | 0052002C3038510634333935 | /dev/ttyACM0    |
| nucleo_g0b1re   | 066AFF485753667187204956 | /dev/ttyACM2    |
| nucleo_l476rg   | 0673FF3732584B3043222412 | /dev/ttyACM3    |

INFO    - JOBS: 32
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
ERROR   - nucleo_g0b1re             tests/lib/spsc_pbuf/libraries.spsc_pbuf             FAILED : Failed
ERROR   - see: /home/abram/Workspaces/zephyr-rtos/twister-out/nucleo_g0b1re/tests/lib/spsc_pbuf/libraries.spsc_pbuf/handler.log
ERROR   - nucleo_l476rg             tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc.fpu  FAILED : Timeout
ERROR   - see: /home/abram/Workspaces/zephyr-rtos/twister-out/nucleo_l476rg/tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc.fpu/handler.log
INFO    - Total complete: 5838/5838  100%  skipped: 4655, failed:    2, error:    0
INFO    - 2151 test scenarios (5838 test instances) selected, 4655 configurations skipped (4458 by static filter, 197 at runtime).
INFO    - 1181 of 5838 test configurations passed (99.83%), 2 failed, 0 errored, 4655 skipped with 0 warnings in 3216.34 seconds
INFO    - In total 15705 test cases were executed, 35741 skipped on 3 out of total 3 platforms (100.00%)
INFO    - 1183 test configurations executed on platforms, 0 test configurations were only built.
```

**Comment by erwango** [comment]
> That's what I mean: The new ST code now has it's own "patch" to not redefine UNUSED if it already has been.

Ok, I've missed that actually. So in this case, let's take the Cube official code and clean the patch list in README file. The interest of those patches is only for the time waiting for fixes to be officially delivered.

**Comment by legoabram** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/78249

I'll fix the comment compliance when I have to update it anyway.

**Review by gautierg-st — APPROVED** [review]

**Pull request merged**
