### PR TITLE
stm32cube: Disable Legacy CAN API

### PR DESCRIPTION
**Pull request by erwango**
Remove fixes on Cube packages to use Legacy API.
Applied to STM32F0, F1, F3, F4, F7 and L4.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
@alexanderwachter

**Comment by erwango** [comment]
@galak, FYI @alexanderwachter is preparing a driver update to go with this change, we need to wait for his patch before merging this one.

**Comment by alexanderwachter** [comment]
Driver (#17229) is ready.

**Comment by erwango** [comment]
Could be merged safely following merge of zephyrproject-rtos/zephyr#17229

**Pull request merged**
