### PR TITLE
dts: update pinctrl files to latest cubemx

### PR DESCRIPTION
**Pull request by gmarull**
Update pinctrl files based on CubeMX 6.1.0 release.

Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>

### CODE REVIEW

**Comment by Nukersson** [comment]
My PR #29680 blocked by this one.

**Review by erwango — CHANGES_REQUESTED** [review]
Please update dts/README with the new CubeMx reference

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@Nukersson is this approved from your side ?

**Comment by Nukersson** [comment]
> @Nukersson is this approved from your side ?

@erwango Worked with h723 like a charm.

**Review by Nukersson — APPROVED** [review]
LGTM

**Pull request merged**
