### PR TITLE
make stm32cube a zephyr_library()

### PR DESCRIPTION
**Pull request by marc-hb**
Stops leaking very long source paths in build directories; makes them
deterministic.

This is identical to what was already merged in
https://github.com/zephyrproject-rtos/hal_nordic/pull/6
or https://github.com/zephyrproject-rtos/zephyr/pull/19531
see previous code reviews there.

See also CMake issue https://gitlab.kitware.com/cmake/cmake/issues/19475
for more details.

This is basically a search/replace of "zephyr_sources" with
"zephyr_library_sources"

For instance, when running sanitycheck -p stm3210c_eval, this changes
the build directories from:
```
sample.helloworld/
└── zephyr
    ├── CMakeFiles
    │   │   ├── HOME
    │   │   │   └── JOHN
    │   │   │      └── ZEPHYRPROJECT
    │   │   │          └── modules
    │   │   │             └── hal
    │   │   │                └── stm32
    │   │   │                    └── stm32cube
    │   │   │                       └── stm32f1xx
    │   │   │                          ├── drivers
    │   │   │                          │  └── src
    │   │   │                          │     ├── stm32f1xx_hal.c.obj
    │   │   │                          │     ├── stm32f1xx_hal_rcc.c.obj
    │   │   │                          │     └── stm32f1xx_ll_utils.c.obj
    │   │   │                          └── soc
    │   │   │                              └── system_stm32f1xx.c.obj
```
... to:
```
sample.helloworld/
├── modules
│   ├── stm32
│   │   ├── CMakeFiles
│   │   └── stm32cube
│   │       ├── CMakeFiles
│   │       │   └── ..__modules__hal__stm32__stm32cube.dir
│   │       │       └── stm32f1xx
│   │       │           ├── drivers
│   │       │           │   └── src
│   │       │           │       ├── stm32f1xx_hal.c.obj
│   │       │           │       ├── stm32f1xx_hal_rcc.c.obj
│   │       │           │       └── stm32f1xx_ll_utils.c.obj
│   │       │           └── soc
│   │       │               └── system_stm32f1xx.c.obj
│   │       ├──
│   │       ├── lib..__modules__hal__stm32__stm32cube.a
```
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
All green CI there: https://github.com/zephyrproject-rtos/zephyr/pull/19662

Fixes #19614

I can't add reviewers in this repo, @erwango can you help?

**Comment by avisconti** [comment]
So we should do the same for 'modules/hal/st/'

**Comment by marc-hb** [comment]
Hi , could we get this in? Because of the number of (identical) lines, this commit has been in the past more painful to rebase than the other, similar ones...

**Comment by erwango** [comment]
@zephyrproject-rtos/maintainers

**Pull request merged**
