### PR TITLE
pins: dts: Add missing USB_OTG_FS_ID pin

### PR DESCRIPTION
**Pull request by galak**
Add USB_OTG_FS_ID to config.yaml and re-gen dts pinctrl.dtsi files

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
- F1 config file should also be updated
- It looks like `pull-up` is necessary: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pinmux/stm32/pinmux_stm32l5x.h#L37

**Comment by galak** [comment]
> * F1 config file should also be updated
> * It looks like `pull-up` is necessary: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pinmux/stm32/pinmux_stm32l5x.h#L37

for F1 is I set `pull-up` I get:

`ValueError: Bias can only be set for input mode on F1 (entry: USB_OTG_FS_ID)`

**Comment by gmarull** [comment]
> for F1 is I set `pull-up` I get:
> 
> `ValueError: Bias can only be set for input mode on F1 (entry: USB_OTG_FS_ID)`

F1 has some special rules compared to the rest of families (see the docs in the F1 config file). In this case it should be configured as an `input` + `pull-up`.

**Comment by galak** [comment]
> F1 has some special rules compared to the rest of families (see the docs in the F1 config file). In this case it should be configured as an `input` + `pull-up`

Fixed.

**Comment by gmarull** [comment]
@galak seems like script needs to be re-run, no changes are present for F1

**Comment by galak** [comment]
> @galak seems like script needs to be re-run, no changes are present for F1

I re-ran, doesn't change anything for F1.

**Comment by gmarull** [comment]
@galak all USB stuff from F1 config file can actually be deleted, it's not used.

**Comment by galak** [comment]
> @galak all USB stuff from F1 config file can actually be deleted, it's not used.

Updated to remove USB stuff from f1.

**Review by gmarull — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Please split the initial commit in 2, so that scripts/genpinctrl/config.yaml could be reviewed easily.

@gmarull Maybe we'll need to add a GH Action to check this ?

**Comment by galak** [comment]
> Please split the initial commit in 2, so that scripts/genpinctrl/config.yaml could be reviewed easily.
> 
> @gmarull Maybe we'll need to add a GH Action to check this ?

Sure thing.

**Review by erwango — APPROVED** [review]

**Pull request merged**
