### PR TITLE
scripts: genpinctrl: use pathlib

### PR DESCRIPTION
**Pull request by gmarull**
Use pathlib facilities to improve path handling. Also added defaults to make it easier to use the script.

### CODE REVIEW

**Comment by erwango** [comment]
^^@ABOSTM

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by galak** [comment]
@erwango any review from you?

**Review by erwango — APPROVED** [review]
Tested ok on Linux

**Comment by gmarull** [comment]
@galak ping

**Pull request merged**
