### PR TITLE
Stm32 cube updates: f0, f1, f2, f3, f4, f7, l0, l1, g0, wb, wl 

### PR DESCRIPTION
**Pull request by ABOSTM**
STM32Cube updates:

stm32cube: update stm32f1 to version V1.8.4
stm32cube: update stm32f2 to version V1.9.3
stm32cube: update stm32f4 to version ~~V1.26.1~~ V1.26.2
stm32cube: cleanup stm32f7 version V1.16.1
stm32cube: update stm32g0 to version V1.5.0
stm32cube: update stm32wl to version V1.1.0
[Edit:] and also
stm32cube: update stm32f0 to version V1.11.3
stm32cube: update stm32f3 to version V1.11.3
stm32cube: update stm32l0 to version V1.12.1
stm32cube: update stm32l1 to version V1.10.3
stm32cube: update stm32wb to version V1.12.0  (including ble library update)
stm32cube: common_ll: Regeneration after cube updates

### CODE REVIEW

**Comment by ABOSTM** [comment]
Cleanup stm32f7 (instead of update)

**Review by FRASTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by ABOSTM** [comment]
Rebase after merge of https://github.com/zephyrproject-rtos/hal_stm32/pull/111

**Review by str4t0m — COMMENTED** [review]
STM32G0:
The patch "-added include guards to stm32g0xx_hal_hcd.h(STM32CubeG0 GH issue: 13)" was resolved upstream so the remark could be removed from the stm32cube/stm32g0xx/README file.

**Comment by ABOSTM** [comment]
> STM32G0:
> The patch "-added include guards to stm32g0xx_hal_hcd.h(STM32CubeG0 GH issue: 13)" was resolved upstream so the remark could be removed from the stm32cube/stm32g0xx/README file.

Right, I missed it.
Fixed. Thanks

**Review by str4t0m — APPROVED** [review]

**Comment by ABOSTM** [comment]
Sorry, pushed on the wrong branch. revert to a698488

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
