### PR TITLE
stm32cube: Add HAL for the STM32G4x series

### PR DESCRIPTION
**Pull request by rosterloh**
This commit adds the STM32CUBE HAL for STM32G4x series MCUs.

Signed-off-by: Richard Osterloh <richard.osterloh@gmail.com>

### CODE REVIEW

**Comment by erwango** [comment]
DNM, waiting for matching PR in main repo going through CI.

**Comment by ioannisg** [comment]
@erwango is the a PR that builds Zephyr with the head of this PR?

**Comment by ioannisg** [comment]
is it #18806?

**Comment by rosterloh** [comment]
Yes it is

**Pull request merged**
