### PR TITLE
dts: Add DFSDM pins to pinctrl.dtsi files

### PR DESCRIPTION
**Pull request by charliegilliland**
I'm working on a dmic driver for Zephyr which will use DFSDM, so this adds those pins to the dtsi files and updates the config.yaml.

### CODE REVIEW

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@charliegilliland Would you min generating a new batch of -pinctrl.dtsi files based on latest top of this repo (05ee82ff431deefc32322cccf112b9b6aff4aec6) ?
We've just merged STM32H7RS pin control files and they would be impacted by you change.
Thanks

**Comment by charliegilliland** [comment]
@erwango Sure thing, see my latest commits here.

**Comment by erwango** [comment]
> @erwango Sure thing, see my latest commits here.

Thanks @charliegilliland but this will require a bit more git'nastic ;) :
We'll still the changes in 2 commits:
- script
- batch of new files
Also we don't take merge branches, so what you'd need to do is to edit the second of your initial commits and get the changes files here.
Depending on your state of tree the most simple might be to take the first commit on top of the new main, launch a new generation and make the new second commit from there.

**Review by erwango — CHANGES_REQUESTED** [review]
See latest comment

**Comment by charliegilliland** [comment]
@erwango OK, I did a rebase and re-generated the dtsi files. How does this look?
Thanks for your patience as I'm somewhat new to this workflow!

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> How does this look?

Perfect thanks.

> Thanks for your patience as I'm somewhat new to this workflow!

No issue, this is quite usual.

**Pull request merged**
