### PR TITLE
stm32cube: rtc: Fix bit operations in LL_RTC_DATE_Config()

### PR DESCRIPTION
**Pull request by takumiando**
Currently, Zephyr doesn't need to apply this patch.
But it may need to do in the future.

Actually I need this patch for my own application :)

### CODE REVIEW

**Comment by erwango** [comment]
Thanks @takumiando.
Maybe it would be better to push this change directly in STM32Cube repos:
https://github.com/STMicroelectronics/STM32CubeF4

**Comment by takumiando** [comment]
@erwango Should I push to all STM32Cube series?

**Comment by erwango** [comment]
> @erwango Should I push to all STM32Cube series?

This has to be discussed with maintainers. But at least push on the one series you're interested in.

**Comment by takumiando** [comment]
Okay ;)

**Pull request closed without merging**
